-- 코드를 입력하세요
SELECT O.PRODUCT_ID,P.PRODUCT_NAME,SUM(O.AMOUNT * P.PRICE) AS TOTAL_SALES
FROM FOOD_ORDER O left join FOOD_PRODUCT AS P on O.PRODUCT_ID = P.PRODUCT_ID
WHERE YEAR(O.PRODUCE_DATE) = 2022 AND MONTH(O.PRODUCE_DATE) = 5 AND P.PRODUCT_NAME is not null
GROUP BY O.PRODUCT_ID 
ORDER BY TOTAL_SALES DESC ,O.PRODUCT_ID ASC