-- 코드를 입력하세요
SELECT A.APNT_NO,P.PT_NAME,P.PT_NO,A.MCDP_CD,D.DR_NAME,A.APNT_YMD

FROM 
(SELECT * 
 FROM APPOINTMENT
WHERE DATE_FORMAT(APNT_YMD,"%Y-%m-%d") = "2022-04-13" AND APNT_CNCL_YN = "N" AND MCDP_CD = "CS") A 
left join DOCTOR D on A.MDDR_ID = D.DR_ID 
left join PATIENT P on A.PT_NO = P.PT_NO
ORDER BY A.APNT_YMD ASC


